верстка
LSD237/restaurant pull request #1
Opened 2018-11-06 13:22 UTC by LSD237

2018-11-13 12:34 UTC, SuperOleg39 requested changes

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +        <link rel="stylesheet" href="style.css">
не хватает meta viewport тега, как в прошлой верстке

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
Где сам логотип?

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <li><a href="Home">Home</a></li>
тут в href, во всех id и классах ниже, не надо использовать большие буквы, так не принято)

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <li><a href=""><img src="" alt=""></a></li>
вырежи иконки как одну картинку, так уж и быть

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                <img src="" alt="">
где картинка?

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                <div class="button">
класс button очень общий. И плюс у тебя две кнопки тут, назови его home-buttons

для кнопок создай общий класс типа .button с размерами и прочим, и два класса модификатора - .button--dark и .button--light например, которые уже цвет фона и шрифта зададут

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
картинки нет

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <img src="" alt="">
и тут нет

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <h2>just the right food</h2>
под этим заголовком картинка же

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                <div class="About-content">
.About-content и загадочный - .img.... - это колонки, с одинаковым размером, создай общий класс для них

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <img src="" alt="">
лентяй

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                            <p class="nomination">Tzatsiki</p><p class="nomination">$3.99</p>
классы у обоих одинаковые nomination, но первый прижат к левому краю, а второй к правому

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                            <img src="" alt="">
это не картинка, просто нижняя граница

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                            <p class="nomination">Tzatsiki</p><p class="nomination">$3.99</p>
и им нужен родительский элемент

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <h2>Guest Reviews</h2>
картинка ниже

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <p>-food inc, New York</p>
как ты поймешь, что конкретно этот текст надо меньше размером сделать?

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +        <section class="section-reviews">
тут много секций, у которых во весь экран фоновое изображение, изучи свойство background-image и все производные от него, и сделай универсальный класс, типа .cover-background, который правильно растягивает и позиционирует фоновое изображение

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
тут внутри тоже строка и колонки, в которых уже картинки

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                    <h2>Just the right food</h2>
вот тебе идея. Много одинаковых заголовков, с этим узором под ним. Создай один класс для заголовков, для него создай стили с псевдо-элементом ::before или ::after, и для этого псевдо элемента через background-image задавай картинку узора

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <form action="" method="POST">
это одна форма, а не четыре разны, и action и method можно не указывать

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                            <label>Name<input type="text" name="email" value="your email*"></label>
type="email"

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                            <label>Date<input type="text" name="date" value="date*"></label>
если не заморачиваться - type="date"

а вообще тебе нужно сделать один контейнер для инпутов, и дополнительные классы, которые будут иконки через псевдо элементы добавлять,типа такого

```
<div class="field field-date">
  <label for="date">Your birthday</label>
  <input id="date" />
</div>```

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                        <button>Book now!</button>
button type="submit" внутри формы

2018-11-13 12:34 UTC, SuperOleg39 commented on index.html
> +                <h3>About Us</h3>
и тут везде этот универсальный класс заголовка пригодится

2018-11-19 16:11 UTC, LSD237 commented on index.html
> +                    <img src="" alt="">
Дэк вот же в див с классом logo вложена img  которая и есть логотип, так же в прошлый раз делали...

2018-11-19 17:47 UTC, LSD237 commented on index.html
> +                <h3>About Us</h3>
какой еще "этот" и зачем?

2018-11-19 17:50 UTC, LSD237 commented on index.html
> +                            <label>Date<input type="text" name="date" value="date*"></label>
надеюсь сделал правильно, пока не вкуриваю как будет выглядеть добавление иконок

2018-11-19 17:57 UTC, LSD237 commented on index.html
> +                            <label>Name<input type="text" name="email" value="your email*"></label>
а в http://htmlbook.ru этого неть

2018-11-19 19:02 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
я имею в виду ссылку на саму картинку)

2018-11-19 19:04 UTC, SuperOleg39 commented on index.html
> +                            <label>Name<input type="text" name="email" value="your email*"></label>
https://html5book.ru/html5-forms/

2018-11-19 19:06 UTC, SuperOleg39 commented on index.html
> +                <h3>About Us</h3>
это отсылка к комментарию https://github.com/LSD237/restaurant/pull/1#discussion_r233015671

2018-11-20 15:27 UTC, LSD237 commented on index.html
> +        <link rel="stylesheet" href="style.css">
разве его не логично начинать не сразу пихать, а на стадии адаптации, когда уже CSS подходит к концу или это мувитон?

2018-11-20 19:37 UTC, LSD237 commented on index.html
> +                        <img src="" alt="">
в каком плане?

2018-11-20 19:45 UTC, LSD237 commented on index.html
> +                    <img src="" alt="">
не понял, опиши подробнее

2018-11-20 19:55 UTC, LSD237 commented on index.html
> +                    <h2>Just the right food</h2>
т.е. из html убрать img под заголовками? (одинаковых там 8 шт (h2))

2018-11-20 19:57 UTC, LSD237 commented on index.html
> +                    <h2>Just the right food</h2>
т.е. из html убрать img под заголовками? (одинаковых там 8 шт (h2))
Под всеми заголовками картинки убрать?

2018-11-20 20:03 UTC, LSD237 commented on index.html
> +                        <img src="" alt="">
в каком плане? нужно было каждую img в div запихать?

2018-11-21 08:00 UTC, SuperOleg39 commented on index.html
> +        <link rel="stylesheet" href="style.css">
не знаю кто такой мувитон, но пихать надо сразу, и сайт сразу адаптивным делать, и вообще с мобильной версии разрабатывать))

2018-11-21 08:02 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
reservations-column - две колонки по 50%

img внутри первой - тоже оба по 50%, значит нужны строка и колонка для каждого img, с 50% ширины

2018-11-21 08:02 UTC, SuperOleg39 commented on index.html
> +                    <h2>Just the right food</h2>
как только сможешь реализовать такой класс, конечно убирай

2018-11-21 14:30 UTC, LSD237 commented on index.html
> +                    <img src="" alt="">
каждый img засунул в div(который тоже по 50%), этого не хватит? Не догоняю, что за строка и как ее реализовать?

2018-11-23 10:59 UTC, SuperOleg39 commented on index.html
> +                        <img src="" alt="">
не, каждому src нужно

2018-11-23 11:00 UTC, SuperOleg39 commented on index.html
> +                    <img src="" alt="">
строка - считай контейнер.

ну вообще, есть привычные понятия из таблиц - строки и столбцы (колонки), их и использую.

короче начнешь верстать, ясно будет. достаточно или нет)

2018-11-23 11:08 UTC, SuperOleg39 commented on index.html
> +                                <!-- как в css "в картинке" (то что товар рекомендуется) расместить блюдо? -->
Если ты про Special слово - сделай класс dishes--special, и через ::after этому классу добавляешь элемент с content: 'Special'

2018-11-23 11:22 UTC, SuperOleg39 approved these changes

2018-11-23 11:34 UTC, merged